# Generated by Django 5.1.5 on 2025-02-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="date_joined",
            field=models.DateField(null=True),
        ),
    ]
