# Generated by Django 5.1.5 on 2025-04-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "tasks",
                    models.ManyToManyField(
                        related_name="calendar_dates", to="tasks.task"
                    ),
                ),
            ],
        ),
    ]
