# Generated by Django 5.1.5 on 2025-04-10 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calendardate",
            name="tasks",
        ),
    ]
