# Generated by Django 5.1.5 on 2025-04-15 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="achievement",
            old_name="title",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="achievement",
            name="badgetype",
        ),
        migrations.RemoveField(
            model_name="achievement",
            name="earned",
        ),
        migrations.RemoveField(
            model_name="achievement",
            name="earned_on",
        ),
        migrations.RemoveField(
            model_name="achievement",
            name="user",
        ),
        migrations.RemoveField(
            model_name="achievement",
            name="value",
        ),
        migrations.AddField(
            model_name="achievement",
            name="description",
            field=models.TextField(default="Completed a task."),
        ),
        migrations.AddField(
            model_name="achievement",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="achievements", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
