# Generated by Django 5.1.5 on 2025-04-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0002_rename_title_achievement_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="achievement",
            old_name="users",
            new_name="user",
        ),
        migrations.AddField(
            model_name="achievement",
            name="earned",
            field=models.BooleanField(default=False),
        ),
    ]
