# Generated by Django 5.1.5 on 2025-04-15 14:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0003_rename_users_achievement_user_achievement_earned"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="earned_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
